JCC = javac
JFLAGS = -g
default: GameTester.class Game.class Place.class Direction.class AI.class Character.class CleanLineScanner.class DecisionMaker.class KeyboardScanner.class Move.class NPC.class Player.class UI.class UserInterface.class TextInterface.class IO.class GUI_J.class GUI_M.class GUI_C.class

GameTester.class: GameTester.java
	$(JCC) $(JFLAGS) GameTester.java
Game.class: Game.java
	$(JCC) $(JFLAGS) Game.java
Place.class: Place.java
	$(JCC) $(JFLAGS) Place.java
Direction.class: Direction.java
	$(JCC) $(JFLAGS) Direction.java
Artifact.class: Artifact.java
	$(JCC) $(JFLAGS) Artifact.java
AI.class: AI.java
	$(JCC) $(JFLAGS) AI.java
Character.class: Character.java
	$(JCC) $(JFLAGS) Character.java
CleanLineScanner.class: CleanLineScanner.java
	$(JCC) $(JFLAGS) CleanLineScanner.java
DecisionMaker.class: DecisionMaker.java
	$(JCC) $(JFLAGS) DecisionMaker.java
KeyboardScanner.class: KeyboardScanner.java
	$(JCC) $(JFLAGS) KeyboardScanner.java
Move.class: Move.java
	$(JCC) $(JFLAGS) Move.java
NPC.class: NPC.java
	$(JCC) $(JFLAGS) NPC.java
Player.class: Player.java
	$(JCC) $(JFLAGS) Player.java
UserInterface.class: UserInterface.java
	$(JCC) $(JFLAGS) UserInterface.java
IO.class: IO.java
	$(JCC) $(JFLAGS) IO.java
TextInterface.class: TextInterface.java 
	$(JCC) $(JFLAGS) TextInterface.java
UI.class: UI.java
	$(JCC) $(JFLAGS) UI.java
GUI_C.class: GUI_C.java
	$(JCC) $(JFLAGS) GUI_C.java
GUI_J.class: GUI_J.java
	$(JCC) $(JFLAGS) GUI_J.java
GUI_M.class: GUI_M.java
	$(JCC) $(JFLAGS) GUI_M.java
clean:
	$(RM) *.class
